accounting/urls.py
from django.urls import path
from django.contrib import admin
from . import views

admin.autodiscover()

urlpatterns = [
    path('', views.accounting, name='accounting'),
    path('table/', views.ajaxtable, name='table'),
    path('accounting_pie/', views.ajaxpie, name='pie')
    ]

login/urls.py
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
path('', views.login, name='first'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('login.urls'), name='first_login'),
    path('home/', include('datavis.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('overview/', include('tracking.urls'),name = 'overview'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('options/', include('options.urls'), name='options'),
    path('calendar/', include('calender.urls'), name='calendar'),
    path('acc/', include('accounting.urls'), name='accounting'),
    path('controlling/', include('controlling.urls'), name='controlling'),
]

tracking/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from calender.models import CalendarEvent
from datetime import datetime
from django.db.models import Sum
from django.core.exceptions import ObjectDoesNotExist


class User_limitations(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    limit = models.IntegerField(("Beschränkung in Montaten"), default=5)
    
    def __str__(self):
        return str(self.limit)

class Workingtime(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    workingtime = models.IntegerField(("Arbeitszeit pro Woche"), blank=True)

    def __int__(self):
        return self.user_id

    def get_wk_employ_month(self):
        current_date = datetime.today()
        current_year= current_date.year
        current_month = current_date.month
        wk_per_month = CalendarEvent.objects.filter(start__year=current_year,
                                                    start__month=current_month,
                                                    user_id=self.user_id).aggregate(Sum('hours'))
        try:
            wk_time = self.workingtime
        except ObjectDoesNotExist:
            wk_time = 0

        wk_max = wk_time * 4.35

        if wk_per_month['hours__sum'] is None:
            wk_per_month['hours__sum'] = 0

        wk_per_month_prec = round(float(wk_per_month['hours__sum']) * 100 / wk_max,2)


        wk_max = "{0}".format(str(round(wk_max, 1) if wk_max % 1 else int(wk_max)))
        wk_per_month['hours__sum'] = "{0}".format(str(round(wk_per_month['hours__sum'], 1) if wk_per_month['hours__sum'] % 1 else int(wk_per_month['hours__sum'])))

        wk_result = {
            'wk_month_perc': wk_per_month_prec,
            'wk_per_month': wk_per_month['hours__sum'],
            'wk_max': wk_max}

        return wk_result


class Categorie(models.Model):
    cat = models.CharField(("Typ"),max_length=200)

    def __str__(self):
        return self.cat


class KategorieElement(models.Model):
    kat_element = models.CharField(("Element"), max_length=200, default=None)

    def __str__(self):
        return self.kat_element

class Kategorie(models.Model):
    kategorie = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.kategorie

class Calc_Choices(models.Model):
    calc = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.calc

class Element(models.Model):
    categories = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    wie = models.TextField(max_length=100, default=None, null=True)
    obj = models.TextField( max_length=100, default=None, null=True)
    element = models.ForeignKey(KategorieElement, on_delete=models.CASCADE, default=None)
    calc = models.ForeignKey(Calc_Choices, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return str(self.element)

class ElementTOKat(models.Model):
    katgroup = models.ForeignKey(Kategorie, on_delete=models.CASCADE)
    ele = models.ForeignKey(KategorieElement, on_delete=models.CASCADE)

class FavoriteElement(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    fav_element = models.ForeignKey(Element, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user_id)

accounting/forms.py
from django.contrib.auth.models import User
from tracking.models import Categorie, Element
from django import forms

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username']


class CategorieForm(forms.ModelForm):

    class Meta:
        model = Categorie
        fields = ['cat']

class WieForm(forms.Form):
    class Meta:
        model = Element
        field = ['wie']

class ObjForm(forms.Form):
    class Meta:
        model = Element
        field = ['obj']

accounting/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from tracking.models import Categorie, Element, Calc_Choices
from django_tables2.config import RequestConfig
from .tables import TrackingTable
from calender.models import CalendarEvent




def accounting(request):

    '''
    Get date for choices from the models.

    If a choice field is changing, a ajax function will
    rendering the table with the given data choices.
    '''
    user = User.objects.all().order_by('username')
    cat = Categorie.objects.all().order_by('cat')
    wie = list(set(Element.objects.all().order_by('wie').values_list('wie', flat=True)))
    obj = list(set(Element.objects.all().order_by('obj').values_list('obj', flat=True)))
    
    

    return render(request, 'accounting/accounting.html',
                  {'form': user,
                   'categories': cat,
                   'wie': wie,
                   'obj': obj
                })

def ajaxpie(request):

    if request.method == 'POST':

        pie_data = 0

    return render(request, 'accounting/accounting_pie.html',
                  {'pie_data': pie_data}
                  )

def ajaxtable(request):
    print("ACTION")
    if request.method == "POST":

        '''
        Integrate the user choice field
        if nothing selected the empty list set to all users       
        '''

        user_name = request.POST.getlist("user[]")

        '''
        Get the value from the categorie choice
        '''
        cat_choice = request.POST.getlist("ca[]")

        '''
        Get the value from the Wie choice
        '''
        wie_choice = request.POST.getlist("wie[]")

        '''
        Get the value from the Wie choice
        '''
        obj_choice = request.POST.getlist("obj[]")

        '''
        Get the value from the start and end date choice
        '''

        start_date = request.POST.getlist("start_date")[0]

        end_date = request.POST.getlist("end_date")[0]
        

        '''
        Get the Tracking data correspoonding on the user choice
        '''

        obj = CalendarEvent.objects.filter(user_id__username__in=user_name)

        '''
        Filter the data corresonding to the disired time
        '''

        if start_date and end_date:
            obj = obj.filter(start__year=start_date.split("-")[1], start__month__gte=start_date.split("-")[0])
            obj = obj.filter(end__year=end_date.split("-")[1], end__month__lte=end_date.split("-")[0])


        obj = obj.filter(type__in=cat_choice)

        '''
        Generate the data for the table
        '''
        import pandas as pd
        from django.db.models import Sum
        #calc = Calc_Choices.objects.all().values_list('calc', flat=True)

        agg = obj.values('user_id__username', 'title', 'calc', 'type').annotate(Sum('hours')).order_by(
            'user_id__username', 'title', 'type')


        agg_title = agg.values('user_id__username', 'title', 'type').annotate(Sum('hours')).order_by(
            'user_id__username', 'title', 'type')

        id = 1
        data = []

        '''
        Build a table with the following structure

        Name    Wie     Obj     element     hours_ges       hours_per_cost

        __

        -Names, element and hours_per_cost comes from calendar model
        -Wie and Obj from the Element model
        -hours_ges and hours_per_cost are aggregated from the calendar model 
        '''

        for row in agg:
            id = + 1
            print(row)
            agg_ges = agg_title.filter(user_id__username=row['user_id__username'], title=row["title"], type=row["type"]).first()
            print(agg_ges)


            ele_obj = Element.objects.filter(element__kat_element=row['title'], categories__cat=row["type"],
                                             obj__in=obj_choice, wie__in=wie_choice).first()

            if ele_obj == None:
                wie = None
                obj = None
            else:
                wie = ele_obj.wie
                obj = ele_obj.obj

            data_row = {'id': str(id), "Name": row['user_id__username'], 'Wie': wie, 'Objekt': obj,
                        'Typ': row['type'], 'Kategorie': row['title'], 'Gesamt': str(agg_ges['hours__sum'])}

            data_row.update({x['calc']: str(x['hours__sum']) for x in agg.filter(title=row["title"],
                                                                                 type=row["type"],
                                                                                 user_id__username=row['user_id__username'])})
            if data_row not in data:
                data.append(data_row)

        ges_sum = {}
        calc = []
        for d in data:
            for key, value in d.items():
                if key != 'Name' and key != 'Wie' and key != 'Objekt' and key != 'Typ' and key != 'id' and key != 'Kategorie':
                    calc.append(key)
                    print(key)
                    try:
                        ges_sum[key] = ges_sum[key] + float(value)
                    except (KeyError):
                        ges_sum[key] = 0 + float(value)
        print(ges_sum)
        data.append({**{'Name': '', 'Wie': '', 'Objekt': '', 'Typ': '', 'id': '', 'Kategorie': ''}, **ges_sum})
        calc = set(calc)
        print(calc)
        import django_tables2 as tables
        table = TrackingTable(data=data, template_name='django_tables2/bootstrap.html',
                              extra_columns=[(str(key), tables.Column()) for key in calc])

        RequestConfig(request).configure(table)
        from django_tables2.export.export import TableExport

        export_format = request.POST.get('_export', None)

        if TableExport.is_valid_format(export_format):
            exporter = TableExport('csv', table)
            return exporter.response('table.{}'.format('csv'))

        RequestConfig(request, paginate={'per_page': 50000}).configure(table)

        return render(request, 'accounting/table.html',
                      {
                          'table': table
                      })

accounting/templates/accounting/accounting.html
{% extends "base.html" %}

{% load querystring from django_tables2 %}
{% block content %}
{% load static %}
<head>
<link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css">
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<div class="row row-eq-height">
    <div class="col">
        <div class="content-container">
            <form method="post">
                <label>Auswahl der Mitarbeiter/-in:
                    <select class="form-control" id = "user_select" multiple data-live-search="true" multiple data-actions-box="true" title="Mitarbeiter/in wählen...">
                        {% for u in form %}
                            <option>{{ u }}</option>
                        {% endfor %}
                    </select>
                </label>
            </form>
            <form method="post" id="id_cat">
                <label>Auswahl der Typen:
                    <select id="cat_select" class="form-control" multiple data-live-search="true" multiple data-actions-box="true" title="Typen wählen">
                        {% for cat in categories %}
                        <option>{{ cat }}</option>
                        {% endfor %}
                    </select>
                </label>
            </form>
            <form method="post" id="id_wie">
                <label>Auswahl der Wirtschaftseinheiten:
                    <select id="wie_select" class="form-control" multiple data-live-search="true" multiple data-actions-box="true" title="WIE wählen">
                        {% for w in wie %}
                        <option>{{ w }}</option>
                        {% endfor %}
                    </select>
                </label>
            </form>
            <form method="post" id="id_obj">
                <label>Auswahl der Objekte:
                    <select id="obj_select" class="form-control" multiple data-live-search="true" multiple data-actions-box="true" title="Objekt wählen">
                        {% for o in obj %}
                        <option>{{ o }}</option>
                        {% endfor %}
                    </select>
                </label>
            </form>
            <label>Zeitraum:</label>
            <div class="input-group input-daterange">
                <input type="text" class="form-control" id="start_date" value="">
                <div class="input-group-addon">bis</div>
                <input type="text" class="form-control" id="end_date" value="">
            </div>
            <button type="submit" id="sub_button" style="margin: 15px; margin-left: 0px; height:13%; width: 20%;" onclick="calculate()" class="btn btn-primary inline" >Berechnen</button>
        </div>
    </div>
    <div class="col">
        <div class="content-container">
            <canvas id="bar-chart" ></canvas>
        </div>
    </div>
</div>

<div id="id_table" class="table-responsive" style="color: white;">

</div>

<script type="text/javascript" language="Javascript" src="{% static 'accounting/js/calculate.js' %}"></script>
<script type="text/javascript" language="Javascript" src="{% static 'accounting/js/gen_pie.js' %}"></script>
<script type="text/javascript" language="Javascript" src="{% static 'accounting/js/selectpicker.js' %}"></script>
<script type="text/javascript" language="Javascript" src="{% static 'accounting/js/download.js' %}"></script>
<script>
    var csrf_token = '{{ csrf_token }}'
</script>
<script src="https://cdn.jsdelivr.net/npm/file-saver@2.0.2/dist/FileSaver.min.js"></script>
<script src="https://rawgit.com/clarketm/js-xlsx/master/xlsx.core.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/js/tableexport.js"></script>
<link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.11/css/tableexport.min.css">

<link rel="stylesheet" href="{% static 'accounting/css/accounting.css' %}" type="text/css">

{% endblock %}

accounting/templates/accounting/table.html
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
<div id="download_div" style="padding: 5px;"></div>

{% render_table table %}

<script>
TableExport.prototype.charset = "charset=utf-8";


// Define the table you want to export
var $myTable = $('table');

$myTable.tableExport({
  headers: true,                     // (Boolean), display table headers (th or td elements) in the <thead>, (default: true)
  footers: true,                      // (Boolean), display table footers (th or td elements) in the <tfoot>, (default: false)
  formats: ["xlsx"],                  // (String[]), filetype(s) for the export, (default: ['xlsx', 'csv', 'txt'])
  filename: "PZW_Kostenverteilung",   // (id, String), filename for the downloaded file, (default: 'id')
  bootstrap: true,                    // (Boolean), style buttons using bootstrap, (default: true)
  exportButtons: true,                // (Boolean), automatically generate the built-in export buttons for each of the specified formats (default: true)
  position: "bottom",                    // (top, bottom), position of the caption element relative to table, (default: 'bottom')
  ignoreRows: null,                   // (Number, Number[]), row indices to exclude from the exported file(s) (default: null)
  ignoreCols: null,                   // (Number, Number[]), column indices to exclude from the exported file(s) (default: null)
  trimWhitespace: true,               // (Boolean), remove all leading/trailing newlines, spaces, and tabs from cell text in the exported file(s) (default: false)
  RTL: false,                         // (Boolean), set direction of the worksheet to right-to-left (default: false)
  sheetname: "Kostenverteilung"       // (id, String), sheet name for the exported spreadsheet, (default: 'id')
});

// Detach the `buttons` html
var $buttons = $myTable.find('caption').children().detach();

// Append the buttons to an element of your choosing
$buttons.appendTo('#download_div');


</script>