login/urls.py
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
path('', views.login, name='first'),
]

options/urls.py
from django.urls import path,re_path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('ajax/load-element/', views.load_elements, name='ajax_load_element'),
    path('', views.options, name='options'),
    path('addfavorites/', views.addfavortites, name='addfavorites'),
    path('admin_options/addcategories/', views.addcategories, name='add_cat'),
    path('admin_options/editcategories/', views.editcategories, name='edit_cat'),
    path('admin_options/deletecategories/', views.deletecategories, name='del_cat'),


    path('admin_options/addelements/', views.addelements, name='add_ele'),
    path('admin_options/editelements/', views.editelements, name='edit_ele'),
    path('admin_options/deleteelements/', views.deleteelements, name='del_ele'),

    path('load_favorites/', views.load_favorites, name='load_favorites'),
    path('admin_options/', views.admin_options, name='admin_options'),
    path('admin_options/load_elements/', views.load_favelements, name='load_elements'),
    #path('admin_options/load_fav/', views.load_fav, name='load_fav'),

    path('admin_options/ajax_save_element/', views.ajax_save_element, name='ajax_save_element'),
    path('admin_options/ajax_add_from_group/', views.ajax_add_from_group, name='ajax_add_from_group'),
    path('admin_options/ajax_load_from_groups/', views.ajax_load_from_groups, name='ajax_load_from_groups'),
    path('admin_options/addcalc/', views.addcalc, name='add_calc'),
    path('admin_options/editcalc/', views.editcalc, name='editcalc'),
    path('admin_options/deletecalc/', views.deletecalc, name='deletecalc'),
    path('admin_options/edit_user/',views.edit_user, name='edit_user'),
    path('admin_options/ajax_load_userdata/',views.ajax_load_userdata, name='ajax_load_userdata'),
    path('admin_options/ajax_delete_user/', views.ajax_delete_user, name='ajax_delete_user'),
    path('admin_options/ajax_user_limit/', views.ajax_user_limit, name='ajax_user_limit'),
    path('admin_options/ajax_load_limit/', views.ajax_load_limit, name='ajax_load_limit'),
    path('admin_options/ajax_load_event_elements/', views.ajax_load_event_elements, name='ajax_load_event_elements'),
    path('admin_options/ajax_save_event_element/', views.ajax_save_event_element, name='ajax_save_event_element'),
    
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('login.urls'), name='first_login'),
    path('home/', include('datavis.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('overview/', include('tracking.urls'),name = 'overview'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('options/', include('options.urls'), name='options'),
    path('calendar/', include('calender.urls'), name='calendar'),
    path('acc/', include('accounting.urls'), name='accounting'),
    path('controlling/', include('controlling.urls'), name='controlling'),
]

tracking/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from calender.models import CalendarEvent
from datetime import datetime
from django.db.models import Sum
from django.core.exceptions import ObjectDoesNotExist


class User_limitations(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    limit = models.IntegerField(("Beschränkung in Montaten"), default=5)
    
    def __str__(self):
        return str(self.limit)

class Workingtime(models.Model):
    user_id = models.OneToOneField(User, on_delete=models.CASCADE)
    workingtime = models.IntegerField(("Arbeitszeit pro Woche"), blank=True)

    def __int__(self):
        return self.user_id

    def get_wk_employ_month(self):
        current_date = datetime.today()
        current_year= current_date.year
        current_month = current_date.month
        wk_per_month = CalendarEvent.objects.filter(start__year=current_year,
                                                    start__month=current_month,
                                                    user_id=self.user_id).aggregate(Sum('hours'))
        try:
            wk_time = self.workingtime
        except ObjectDoesNotExist:
            wk_time = 0

        wk_max = wk_time * 4.35

        if wk_per_month['hours__sum'] is None:
            wk_per_month['hours__sum'] = 0

        wk_per_month_prec = round(float(wk_per_month['hours__sum']) * 100 / wk_max,2)


        wk_max = "{0}".format(str(round(wk_max, 1) if wk_max % 1 else int(wk_max)))
        wk_per_month['hours__sum'] = "{0}".format(str(round(wk_per_month['hours__sum'], 1) if wk_per_month['hours__sum'] % 1 else int(wk_per_month['hours__sum'])))

        wk_result = {
            'wk_month_perc': wk_per_month_prec,
            'wk_per_month': wk_per_month['hours__sum'],
            'wk_max': wk_max}

        return wk_result


class Categorie(models.Model):
    cat = models.CharField(("Typ"),max_length=200)

    def __str__(self):
        return self.cat


class KategorieElement(models.Model):
    kat_element = models.CharField(("Element"), max_length=200, default=None)

    def __str__(self):
        return self.kat_element

class Kategorie(models.Model):
    kategorie = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.kategorie

class Calc_Choices(models.Model):
    calc = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.calc

class Element(models.Model):
    categories = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    wie = models.TextField(max_length=100, default=None, null=True)
    obj = models.TextField( max_length=100, default=None, null=True)
    element = models.ForeignKey(KategorieElement, on_delete=models.CASCADE, default=None)
    calc = models.ForeignKey(Calc_Choices, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return str(self.element)

class ElementTOKat(models.Model):
    katgroup = models.ForeignKey(Kategorie, on_delete=models.CASCADE)
    ele = models.ForeignKey(KategorieElement, on_delete=models.CASCADE)

class FavoriteElement(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    fav_element = models.ForeignKey(Element, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user_id)

options/forms.py
from bootstrap_datepicker_plus import TimePickerInput
from django import forms
from tracking.models import Element, Categorie, Workingtime, Kategorie, Calc_Choices, KategorieElement
from django.contrib.auth.models import User
from options.admin import UserCreationForm
from django import forms
from calender.models import CalendarEvent

class UsereditForm(forms.Form):
    username_pop = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    email_pop = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name_pop = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name_pop = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    working_time_pop = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)
    is_superuser = forms.CheckboxInput()

    class Meta:
        model = User
        fields = ('username', 'email', 'is_superuser')

class CalcForm(forms.ModelForm):
    class Meta:
        model = Calc_Choices
        fields = ['calc']
        widgets = {
            'calc': forms.TextInput(attrs={'class': 'form-control'}),
        }

class calcchoiceForm(forms.Form):
    choice = forms.ModelChoiceField(label='Kostenträger auswählen:', queryset=Calc_Choices.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))

class editCalcForm(forms.Form):
    choice = forms.ModelChoiceField(label="Kostenträger auswählen:",required=True,queryset=Calc_Choices.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    edit = forms.CharField(label="Kostenträger ändern:",required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

class Worktimefrom(forms.ModelForm):
    class Meta:
        model = Workingtime
        fields = ['workingtime']
        widgets = {
            'workingtime': TimePickerInput()
        }

class Categorieform(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = ['cat']
        widgets = {
            'cat': forms.TextInput(attrs={'class': 'form-control'})
        }

class deletecatForm(forms.Form):
    choice = forms.ModelChoiceField(label="Typ auswählen:", queryset=Categorie.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))


class editcatForm(forms.Form):
    choice = forms.ModelChoiceField(label="Typ auswählen:", queryset=Categorie.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    edit = forms.CharField(label="Kostenträger ändern:",required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))


class Categoriechoiceform(forms.Form):
    cat_choice = forms.ModelChoiceField(queryset=Categorie.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control'}),label='')

class EventsCategoriechoiceform(forms.Form):
    event_cat_choice = forms.ModelChoiceField(queryset=CalendarEvent.objects.values_list('type', flat=True).order_by('type').distinct(),
                                    widget=forms.Select(attrs={'class': 'form-control'}),label='')

class Elementform(forms.ModelForm):
    class Meta:
        model = KategorieElement
        fields = ['kat_element']
        widgets = {
            'kat_element': forms.TextInput(attrs={'class': 'form-control'})
        }

class editelechoiceform(forms.Form):
      choice = forms.ModelChoiceField(label="Kategorie auswählen:", queryset=KategorieElement.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))

class Choicefrom(forms.ModelForm):
    class Meta:
        model = Element
        fields = ['categories', 'element']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['element'].queryset = Element.objects.none()


        if 'categories' in self.data:
            try:
                categories_id = int(self.data.get('categories'))
                self.fields['element'].queryset = Element.objects.filter(categories_id=categories_id).order_by('element')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['element'].queryset = self.instance.categorie.element_set.order_by('element')



class Userlimitform(forms.Form):
        users = forms.ModelChoiceField(queryset=User.objects.all(),
                                    widget=forms.Select(attrs={'class': 'form-control'}),label='')


    

options/templates/options/add_form_group.html
<div class="form-group" style="border-top: 1px solid white; padding: 10px;">
    <div class="row">
        <div class="col-1">
            <p style="color: white;">{{ counter }}</p>
        </div>
        <div class="col-4">
            <select class="form-control" id="element_{{ counter }}">
                {% for ele in elements %}
                <option> {{ele}} </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-1">
            <input type="text" class="form-control" id="wie_{{ counter }}">
        </div>
        <div class="col-1">
            <input type="text" class="form-control" id="obj_{{ counter }}">
        </div>
        <div class="col-4">
            <select class="form-control" id="calc_{{ counter }}">
                {% for cal in calc %}
                <option>{{cal}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col">
            <span onclick="del_from_group(this)" style="color: red; float: right; cursor: pointer;" class="glyphicon glyphicon-minus"></span>
        </div>
    </div>
</div>

options/templates/options/addcategories.html
{% extends 'modal_base.html' %}
{% block content %}

<form method="post" id="modal_form" action="addcategories/">
    {% csrf_token %}
    {{ categorieform }}
    <button type="button" onclick="ajax_save()" class="btn btn-primary" >Speichern</button>
</form>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/addelements.html
{% extends 'modal_base.html' %}
{% block content %}

<form method="post" id="modal_form" action="addelements/">
    {% csrf_token %}
    <label>Kategorie:</label>
    {{ elementsform.kat_element }}
    <button type="button" onclick="ajax_save()" class="btn btn-primary" >Speichern</button>
</form>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/ajax_load_from_groups.html
{% for tab in load_table %}
            <div id="from_group_{{ forloop.counter }}" class="form-group" style= "padding: 10px; border-top: 1px solid white;">
                <div class="row">
                    <div class="col-1">
                        <p style="color: white;">{{ forloop.counter }}</p>
                    </div>
                    <div class="col-4" >
                        <select class="form-control" id ="element_{{ forloop.counter }}" >

                            {% for ele in elements %}
                                {% if ele == tab.element %}
                                    <option selected>{{tab.element}}</option>
                                {% else %}
                                <option>{{ele}}</option>
                            {% endif %}
                            {% endfor %}
                        </select>

                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" id = "wie_{{ forloop.counter }}" value="{{tab.wie}}" >
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" id = "obj_{{ forloop.counter }}" value="{{tab.obj}}">
                    </div>
                    <div class="col-4">
                        <select class="form-control" id = "calc_{{ forloop.counter }}">
                            <option selected>{{tab.calc}}</option>
                            {% for cal in calc %}
                                {% if cal != tab.calc %}
                                    <option>{{cal}}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col">
                        <span onclick="del_from_group(this)" style="color: red; float: right; cursor: pointer;" class="glyphicon glyphicon-minus"></span>
                    </div>
                </div>
            </div>
            <script>
                var counter = {{ forloop.counter }};
                if (counter == undefined){
                var counter = 0;
                }
                console.log(counter);

            </script>
            {% endfor %}

options/templates/options/ajax_load_userdata.html
<form method="post" id="modal_form" action="edit_user/">
    {% csrf_token %}
    <p>
        <label for="id_username_pop">Benutzername:</label>
        <select name="username_pop" class="form-control" required="" id="id_username_pop">
        <option value="" >---------</option>
        {% for ob in options%}
            {% if ob.username == userdata.username %}
                <option value="{{ob.id}}" selected="">{{ob.username}}</option>
            {% else %}
                <option value="{{ob.id}}">{{ob.username}}</option>
            {% endif %}
            {% endfor %}
        </select>
    </p>

    <p>
    <label for="id_email_pop">Email:</label>
    <input type="email" class="form-control" name="email_pop" value="{{userdata.email}}" required="" id="id_email_pop">
    </p>

    <p>
    <label for="id_first_name_pop">Arbeitszeit pro Woche</label>
    <input type="text" value="{{workingtime}}" class="form-control" name="working_time_pop" maxlength="30" id="id_working_time_pop">
    </p>

    <p>
    <label for="id_first_name_pop">Vorname:</label>
    <input type="text" value="{{userdata.first_name}}" class="form-control" name="first_name_pop" maxlength="30" id="id_first_name_pop">
    </p>

    <p>
    <label for="id_last_name_pop">Nachname:</label>
    <input type="text" value="{{userdata.last_name}}" class="form-control" name="last_name_pop" maxlength="150" id="id_last_name_pop">
    </p>

    <input type="button" onclick="ajax_save()" class="btn btn-primary inline" style="margin: 10px;" value="Speichern">
    <input type="button" onclick="user_delete()" class="btn btn-danger inline" style="margin: 10px;" value="Benutzer Löschen">
    <p style="color: #d9534f;">Achtung! Beim löschen eines Benutzers werden auch die vom Benutzer bereits erfassten Arbeitzeiten gelöscht</p>

</form>
<script>
    $('#id_email_pop').addClass('form_control');
    $('#id_first_name_pop').addClass('form_control');
    $('#id_last_name_pop').addClass('form_control');
    $('#id_working_time_pop').addClass('form_control');

    $('#id_username_pop').change( function(){
        console.log("CHANGE");
        var selected_user = $(this).children("option:selected").val();
        console.log(selected_user);

        $.ajax({
          type: 'POST',
          url: 'ajax_load_userdata/',
          data:{
          select: selected_user,
          csrfmiddlewaretoken: "{{ csrf_token }}"
          },
          success: function(data){
          console.log(data);
          $('#load_data').html(data);
          }
        });
    });
</script>
<script>
$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
</script>

options/templates/options/deletecategories.html
{% extends 'modal_base.html' %}
{% block content %}

    <form method="post" id="modal_form" action="deletecategories/">
        {% csrf_token %}
        {{ choice }}
        <button type="button" onclick="ajax_save()" class="btn btn-primary" >Löschen</button>
    </form>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
        <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
        {% endfor %}
        {% endif %}
    </div>
{% endblock %}

options/templates/options/deleteelements.html
{% extends 'modal_base.html' %}
{% block content %}

<form method="post" id="modal_form" action="deleteelements/">
    {% csrf_token %}
    {{ choice }}
  <button type="button" onclick="ajax_save()" class="btn btn-primary" >Löschen</button>
</form>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/editcalc.html
{% extends 'modal_base.html' %}
{% block content %}
<form method="post"  id="modal_form" action="editcalc/">
    {% csrf_token %}
    {{ editcalcform }}
    <button type="button" onclick="ajax_save()" class="btn btn-primary" >Speichern</button>
</form>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/editcategories.html
{% extends 'modal_base.html' %}
{% block content %}
<form method="post" id="modal_form" action="editcategories/">
    {% csrf_token %}
    {{ editcatform}}
    <button type="button" onclick="ajax_save()" class="btn btn-primary" >Speichern</button>
</form>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/editelements.html
{% extends 'modal_base.html' %}
{% block content %}
<form method="post" id="modal_form" action="editelements/">
    {% csrf_token %}
    {{ choice }}
    <label>Kategorie ändern:</label>
    {{ editform.kat_element }}
    <button type="button" onclick="ajax_save()" class="btn btn-primary" >Speichern</button>
</form>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} fade in" style="margin-top: 10px;" role="alert">
    <strong{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</Strong>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

options/templates/options/load_favelements.html
{% for fav in fav_kat_element %}
<option>{{ fav }}</option>
{% endfor %}

options/templates/options/load_favorites.html
{% for fav in favorites %}
<option>{{ fav }}</option>
{% endfor %}

options/templates/options/options.html
{% extends 'base.html' %}

{% block content %}
{% load bootstrap3 %}       {# import bootstrap3 #}
{% bootstrap_css %}         {# Embed Bootstrap CSS #}
{% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
{{ form.media }}            {# Adds date-picker required JS and CSS #}

<head>
    <meta charset="UTF-8">
    <title>Favoriten</title>

<style>

.content-container{
    background-color: #2b2b2b;
    border: 1px solid #4b4c4c;
    margin: 10px;
    margin-top: 10px;
    margin-bottom: 10px;
    padding: 20px;
    height. 100%;
}


.fav-changer{
    margin-top: 10px;
    margin-bottom: -5px;
}

.errorlist{
    color: red;
}

#Worktimeform{
    margin-top: 10px;
    margin-bottom: 10px;
}

label{
    color: white;
}

.glyphicon-star{
    color: gold;
}


#glob_cont{
    padding: 10px;
}



</style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</head>



    <div class="content-container">
        {% if saved %}
        <div class="alert alert-success">
            <strong>Success!</strong> Indicates a successful or positive action.
        </div>
        {% endif %}
        <span style="color:white;">Typenauswahl</span>
        <form method="post" id="choiceForm" data-element-url="{% url 'ajax_load_element' %}" novalidate>
            {% csrf_token %}
            {{ choice_form.categories}}
            <span style="color:white;">Kategorie auswählen und Favoriten Hinzufügen</span>
            <select class="form-control" id="id_element" name="groups_old"  multiple="multiple" style="height: 200px;">

            </select>
            <center>
                <div class = "fav-changer">
                    <a><span onclick="favadd()" style="font-size: 150%; color: #337ab7;" class="glyphicon glyphicon-arrow-down"></span></a>
                    <a><span onclick="favremove()" style="font-size: 150%; color: #337ab7;" class="glyphicon glyphicon-arrow-up"></span></a>
                </div>
            </center>
            <span style="color:gold" class="glyphicon glyphicon-star"><span style="color:white"><STRONG>Favoriten</STRONG></span></span>
            <select class="form-control" id="favorite" name="groups_old" multiple="multiple" style="height: 200px;">

            </select>
        </form>
        <button type="submit" id="sub_button" style=" margin: 15px; margin-left: 0px; height: 35px; width: 100px;" onclick="savefav()" class="btn btn-primary" >Speichern</button>

    </div>


    
    <div class="content-container">
        {% if saved %}
        <div class="alert alert-success">
            <strong>Success!</strong> Indicates a successful or positive action.
        </div>
        {% endif %}
        <span style="color:white;">Typenauswahl</span>
        <form method="post" id="choiceForm" data-element-url="{% url 'ajax_load_element' %}" novalidate>
            {% csrf_token %}
            {{ choice_form.categories}}
            <span style="color:white;">Kategorie auswählen und Favoriten Hinzufügen</span>
            <select class="form-control" id="id_element" name="groups_old"  multiple="multiple" style="height: 200px;">

            </select>
            <center>
                <div class = "fav-changer">
                    <a><span onclick="favadd()" style="font-size: 150%; color: #337ab7;" class="glyphicon glyphicon-arrow-down"></span></a>
                    <a><span onclick="favremove()" style="font-size: 150%; color: #337ab7;" class="glyphicon glyphicon-arrow-up"></span></a>
                </div>
            </center>
            <span style="color:gold" class="glyphicon glyphicon-star"><span style="color:white"><STRONG>Favoriten</STRONG></span></span>
            <select class="form-control" id="favorite" name="groups_old" multiple="multiple" style="height: 200px;">

            </select>
        </form>
        <button type="submit" id="sub_button" style=" margin: 15px; margin-left: 0px; height: 35px; width: 100px;" onclick="savefav()" class="btn btn-primary" >Speichern</button>

    </div>


<script>

    $("#id_workingtime").attr('value', "{{workingtime}}");
    $("#id_categories").attr('class', 'form-control');


    $("#id_categories").change(function () {
      $('#favorite').find('option').remove();
      var url = $("#choiceForm").attr("data-element-url");  // get the url of the `load_elements` view
      var categoriesId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/element/)
        data: {
          'categories': categoriesId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_element` view function
          $("#id_element").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });


    $("#id_categories").change(function () {
      $('#favorite').find('option').remove();
      var categoriesId = $(this).val();

      $.ajax({
        url: 'load_favorites/',
        data: {
          'categories': categoriesId
        },
        success: function (data) {
          $("#favorite").html(data);
        }
      });
    });


    function favadd(){

    var cat = document.getElementById("id_element");
    var text = cat.options[cat.selectedIndex].text;
    cat.remove(cat.selectedIndex);


    var x = document.getElementById("favorite");
    var option = document.createElement("option");
    option.text = text;
    x.add(option);

    $('#id_element').prop("selectedIndex",0);

    }

    function favremove(){

    var fav = document.getElementById("favorite");
    var text = fav.options[fav.selectedIndex].text;
    fav.remove(fav.selectedIndex);

    var x = document.getElementById("id_element");
    var option = document.createElement("option");
    option.text = text;
    x.add(option);

    $('#favorite').prop("selectedIndex",0);

    }

    function savefav(){
        var inner = '<i  id="load_icon" class="fa fa-spinner fa-pulse fa-3x fa-fw" style="font-size:18px; color:#f8f9fa;"></i>'

        load_icon = document.getElementById('sub_button');
        load_icon.innerHTML = inner;

        console.log("save");
        var cat = document.getElementById("id_categories");
        var cat = cat.options[cat.selectedIndex].text;
        console.log(cat);

        var fav = document.getElementById("favorite");
        txt = [];
            for (i = 0; i < fav.length; i++) {
            txt = txt + "," + fav.options[i].value;
        console.log(txt);
        };

        $.ajax({
            type: "POST",
            url: 'addfavorites/',
            data: {
            'favorites': txt,
            'categorie': cat,
            csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function(data){
            console.log(load_icon);
            load_icon.innerHTML = "Speichern";


            }
        });
    }

</script>


{% endblock %}